// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuRpXQ3v1YHWuVXR6-VpH4QgZUjqe24Wk',
    appId: '1:801853105115:web:e28b0f1858a3b5590ebdfe',
    messagingSenderId: '801853105115',
    projectId: 'echo-8b612',
    authDomain: 'echo-8b612.firebaseapp.com',
    storageBucket: 'echo-8b612.firebasestorage.app',
    measurementId: 'G-0YYJZMNETC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0wtby5TneF3St3HNmSLN4UFyKA0v0Rso',
    appId: '1:801853105115:android:e9e96ecbc386d6140ebdfe',
    messagingSenderId: '801853105115',
    projectId: 'echo-8b612',
    storageBucket: 'echo-8b612.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9mKNHqdZFfWZvGnh9el4HdpWkTt6LLw4',
    appId: '1:801853105115:ios:b7d853d0250bb66c0ebdfe',
    messagingSenderId: '801853105115',
    projectId: 'echo-8b612',
    storageBucket: 'echo-8b612.firebasestorage.app',
    iosBundleId: 'com.example.echo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9mKNHqdZFfWZvGnh9el4HdpWkTt6LLw4',
    appId: '1:801853105115:ios:b7d853d0250bb66c0ebdfe',
    messagingSenderId: '801853105115',
    projectId: 'echo-8b612',
    storageBucket: 'echo-8b612.firebasestorage.app',
    iosBundleId: 'com.example.echo',
  );
}
